services:
  backend:
    image: ${BACKEND_IMAGE}
    env_file:
      - backend/.env
    restart: unless-stopped
    expose:
      - "8000"

  nginx:
    image: ${NGINX_IMAGE}
    env_file:
      - backend/.env
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
